### ISSUE TITLE
Not sure if it's me

### ISSUE THREAD

**Issue by rylincoln** [fulcrumapp/fulcrum-record-weather#1]
I followed the guide and got the app spun up on heroku and my webhook is sending push notifications properly when i create new records in my sandbox app but i'm getting errors in the node.js app in heroku that look like this.

https://gist.github.com/rylincoln/ac398d19a01fa76016ec

It's probably me doing something wrong.  Line 14 in that gist appears to be the first error in the heroku logs.  Talking about unexpected token for my forecast API key.  Any ideas?

Thanks,
Ry

**Comment by JasonSanford** [comment]
Hey Ry

You'll want to set `forecastApiKey` either explicitly like:

```
var forecastApiKey = '8c26f375c1e2f8279df9724cddaf0399';
```

or reference an environment variable that you've set like:

```
var forecastApiKey = process.env.FORECAST_API_KEY;
```

**Comment by rylincoln** [comment]
OH, thanks Jason!

**Comment by rylincoln** [comment]
Hey Jason,

I got it working.  Thanks a lot!

Cheers,
Ry
